<?xml version="1.0" standalone="no"?>
<!DOCTYPE entity PUBLIC "-//UC Berkeley//DTD MoML 1//EN"
    "http://ptolemy.eecs.berkeley.edu/xml/dtd/MoML_1.dtd">
<entity name="TestExceptionAttribute2" class="ptolemy.actor.TypedCompositeActor">
    <property name="_createdBy" class="ptolemy.kernel.attributes.VersionAttribute" value="10.0.devel">
    </property>
    <property name="_windowProperties" class="ptolemy.actor.gui.WindowPropertiesAttribute" value="{bounds={104, 86, 820, 631}, maximized=false}">
    </property>
    <property name="_vergilSize" class="ptolemy.actor.gui.SizeAttribute" value="[600, 524]">
    </property>
    <property name="_vergilZoomFactor" class="ptolemy.data.expr.ExpertParameter" value="1.0">
    </property>
    <property name="_vergilCenter" class="ptolemy.data.expr.ExpertParameter" value="{300.0, 262.0}">
    </property>
    <property name="DE Director" class="ptolemy.domains.de.kernel.DEDirector">
        <property name="stopTime" class="ptolemy.data.expr.Parameter" value="1.0">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[120.0, 55.0]">
        </property>
    </property>
    <property name="Annotation" class="ptolemy.vergil.kernel.attributes.TextAttribute">
        <property name="text" class="ptolemy.kernel.util.StringAttribute" value="No exception is thrown.">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="{265.0, 75.0}">
        </property>
    </property>
    <property name="TestExceptionAttribute" class="ptolemy.actor.lib.TestExceptionAttribute">
        <property name="correctExceptionMessage" class="ptolemy.data.expr.StringParameter" value=" was initialized and should have handled an exception but did not see any.&#10;  in .TestExceptionAttribute2.TestExceptionAttribute">
        </property>
        <property name="trainingMode" class="ptolemy.actor.parameters.SharedParameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="[180.0, 245.0]">
        </property>
    </property>
    <property name="TestExceptionAttribute2" class="ptolemy.actor.lib.TestExceptionAttribute">
        <property name="correctExceptionMessage" class="ptolemy.data.expr.StringParameter" value=" was initialized and should have handled an exception but did not see any.&#10;  in .TestExceptionAttribute2.TestExceptionAttribute">
        </property>
        <property name="trainingMode" class="ptolemy.actor.parameters.SharedParameter" value="false">
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="{295.0, 325.0}">
        </property>
    </property>
    <entity name="Const" class="ptolemy.actor.lib.Const">
        <doc>Create a constant sequence.</doc>
        <property name="_icon" class="ptolemy.vergil.icon.BoxedValueIcon">
            <property name="attributeName" class="ptolemy.kernel.util.StringAttribute" value="value">
            </property>
            <property name="displayWidth" class="ptolemy.data.expr.Parameter" value="60">
            </property>
        </property>
        <property name="_location" class="ptolemy.kernel.util.Location" value="{170, 155}">
        </property>
    </entity>
</entity>
